#!/usr/bin/env python

import os

os.system("apt-get install figlet")
os.system("clear")
os.system("figlet KOBRA HACK PORT SCANNER")
print("""
Kobra Hack Port Scanner'i İndirdiginiz icin tesekkurler ;)

1) Hizli Tarama
2) Servis ve Versiyon Bilgisi
3) Isletim Sistemi Bilgisi


""")

islemno = raw_input("Islem Numarasini Girin:  ")

if(islemno=="1"):
           hedefip = raw_input("Hedef ip girin:  ")
           os.system("nmap " + hedefip)

elif(islemno=="2"):
           hedefip = raw_input("Hedef ip girin:  ")
           os.system("nmap -sS -sV " + hedefip)
elif(islemno=="3"):
            hedefip = raw_input("Hedef ip girin: ")
            os.system("nmap -0 " + hedefip)
else:
      print("Hatali Secim Yaptin :D")
